language: python

python:
    - "2.7"
    - "3.4"

install:
    - pip install -r bot-requirements.txt

script:
    - py.test app --pep8 app -v --cov-report term-missing
    - py.test bot --pep8 bot -v --cov bot --cov-report term-missing

after_success:
    - coveralls
