language: python

env:
    - NLTK_DATA=$HOME/nltk_data

python:
    - "2.7"
    # - "3.4"  # gevent is failing for 3.4 todo identify all dependencies

before_install:
# Install miniconda to avoid compiling scipy
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -q -n pyenv mkl python=2.7 numpy=1.9.1 scipy nose pyparsing pip flake8
    - source activate pyenv    
    - pip install -r bot-requirements.txt -r app-requirements.txt
    - python ./scripts/download_nltk_data.py

script:
    - make test

after_success:
    - coveralls
