language: python

env:
    - NLTK_DATA=$HOME/nltk_data

python:
    - "2.7"
    # - "3.4"  # gevent is failing for 3.4 todo identify all dependencies

install:
    - pip install -r bot-requirements.txt -r app-requirements.txt
    - sudo apt-get install python-scipy
    - python ./scripts/download_nltk_data.py

script:
    - make test

after_success:
    - coveralls
